### ISSUE TITLE
Should we add a reference to RFC 8200 in the Glossary section?

### ISSUE THREAD

**Issue by EskoDijk** [ietf-wg-snac/draft-ietf-snac-simple#47]
* we use various terms defined there like "node", "router", "host"
* however, making this reference explicit is probably uncommon in IETF drafts (readers are supposed to know this already) - just wanted to check with the authors.

**Comment by Abhayakara** [comment]
We are agreeing that we should have glossary entries for "node" "router and "host". And we should probably call it "Terminology" rather than "Glossary" since that's more common in IETF documents.
