### ISSUE TITLE
Add Security Considerations and IANA Considerations sections

### ISSUE THREAD

**Issue by EskoDijk** [ietf-wg-snac/draft-ietf-snac-simple#50]
For security we may add:
* risk of advertising self-generated ULA prefix? Any specifics?
* if site employs technology like RA-guard, the RAs of our unmanaged stub router will be blocked

**Comment by Abhayakara** [comment]
These sound more like operational considerations than security considerations. I suppose if we want to advise sites that do not want stub routers attaching to block RA, that would make sense, but I don't think that's really a problem unique to stub routers.

Regarding the ULA prefix, the only risk is one we've already addressed: that the prefix could be used for tracking. I think the text on varying prefixes per-link probably needs work, but that addresses the privacy concern.
