### ISSUE TITLE
Decide on the RA flag bit position for "stub router flag" in draft-hui-stub-router-ra-flag-02

### ISSUE THREAD

**Issue by EskoDijk** [ietf-wg-snac/draft-ietf-snac-simple#54]
Although the RA flag bit position is not in SNAC-simple, it has a large impact on implementations of stub routers. Can we  decide on this bit position or take action with 6man WG to come to a decision? (maybe we did already?)

See: 
* https://datatracker.ietf.org/doc/html/draft-hui-stub-router-ra-flag-02#name-stub-router-flag
* https://datatracker.ietf.org/doc/html/draft-hui-stub-router-ra-flag-02#name-iana-considerations

**Comment by darrendukes** [comment]
6man has been asked to adopt draft-hui... 
They have been asked for early allocation of the RA flag bit and choose it's location.
I believe this issue can be closed and allow the progression of draft-hui-stub-router-ra-flag to define the bit position.

**Comment by EskoDijk** [comment]
Issue could be kept open until the position has  been decided? (It was intended as a reminder for this important dependency) @jwhui assigned to this.

**Comment by Neustradamus** [comment]
Linked to:
- https://datatracker.ietf.org/doc/html/draft-ietf-6man-snac-router-ra-flag
- https://github.com/radvd-project/radvd/pull/271
- https://github.com/radvd-project/radvd/pull/287
