### ISSUE TITLE
Requirement to stop sending RAs when in STATE-SUITABLE - why?

### ISSUE THREAD

**Issue by EskoDijk** [ietf-wg-snac/draft-ietf-snac-simple#60]
Current text has for STATE-SUITABLE:

```
 When entering this state, if the router MUST discontinue treating the interface as an Advertising Interface as
	      described in <xref target="RFC4861" section="6.2.2"/>, if it has been doing so.</t>
```

However, the discontinue requirement also prohibits the sending of RAs with RIO to advertise the route to the stub network's prefix. So this requirement seems incorrect - I assume a route to the stub network's prefix will always be advertised.

Also "the router" should be reworded as "the stub router" to avoid ambiguity.

**Comment by EskoDijk** [comment]
FYI @Abhayakara

**Comment by alan-eero** [comment]
when entering in STATE-SUITABLE , the stub-router has two options:
1. Send stub router RAs with only RIO. 
2. Send stub router RAs with both PIO (lifetime=0) and RIO. where PIO is the stub.router own PIO (not to confuse with the discovered suitable on-link prefix)

**Comment by EskoDijk** [comment]
@alan-eero On option 2: I believe that what you mean here is already done in STATE-DEPRECATING - basically once a PIO prefix that had lifetime=30 min is deprecating, it gets advertised with a < 30 minutes time that decreases all the time until it's less than RA_BEACON_INTERVAL. At that point it stops including the PIO.

So there's no need to include PIO while in STATE-SUITABLE.

**Comment by Abhayakara** [comment]
Fixed by 60-stop-sending-ras-state-usable
