### ISSUE TITLE
We need to specify the advertising of routes to deprecated prefixes

### ISSUE THREAD

**Issue by Abhayakara** [ietf-wg-snac/draft-ietf-snac-simple#67]
This is true for both stub and infra RAs. Right now in [5.1.2.3. ](https://www.ietf.org/archive/id/draft-ietf-snac-simple-04.html#section-5.1.2.3)[IP addressability not present on adjacent infrastructure link (STATE-BEGIN-ADVERTISING)](https://www.ietf.org/archive/id/draft-ietf-snac-simple-04.html#name-ip-addressability-not-prese), we talk about advertising routes to prefixes on the network, but don't explicitly include deprecated prefixes. We need to be explicit about this: as long as a prefix is still valid, even if it's not advertised, we need to advertise a route to it.

**Comment by Abhayakara** [comment]
We covered advertising routes to stub links on infrastructure in 60-stop-sending-ras-state-usable.

**Comment by darrendukes** [comment]
Resolution is to not advertise PIO with zero lifetime. BUT keep routing to the deprecated prefix.
06 text is updated.
