### ISSUE TITLE
Editorial: Stub network definition?

### ISSUE THREAD

**Issue by elear** [ietf-wg-snac/draft-ietf-snac-simple#68]
This sentence in the definition of stub network...

>  There is reachability through a stub network router to
>  hosts on the stub network, but there is no reachability through
>  the stub network to any link beyond the stub network link.

is redundant, given the previous sentence and could confuse people to think that devices **on the stub network** would not have connectivity to the infrastructure network.  I'd just remove it.

**Comment by darrendukes** [comment]
06 fixes it
