### ISSUE TITLE
Conflicting text between introduction and stub network definition?

### ISSUE THREAD

**Issue by elear** [ietf-wg-snac/draft-ietf-snac-simple#69]
The introduction states the following:

>    It may be noted that just as you can plug several Home Gateway
   devices together in series to form multi-layer NATs, there is nothing
   preventing the owner of a stub network router from attaching it to a
   stub network as if that network were its infrastructure network....

But the stub network definition explicitly states that:

> a stub network is
    simply any network that does not provide transit within a routing
    fabric. 

Now the introduction goes on to state...

> Nothing in this document is intended to prevent this from
   being done, but neither do we attempt to solve the problems that this
   could create.

I would suggest dropping the introduction text above.  It's confusing, and if someone gets that case working, they can write another draft / publish another RFC.

**Comment by Abhayakara** [comment]
Rather than saying "you could ..." we should say "this is out of scope"

**Comment by darrendukes** [comment]
IETF 120 Conclusion is to move the text to an appendix to record the discussion
