### ISSUE TITLE
Mention RA Guard (RFC 6105) somewhere

### ISSUE THREAD

**Issue by EskoDijk** [ietf-wg-snac/draft-ietf-snac-simple#76]
Given that 

1. we've discussed many times already how RA Guard can be used on networks were the "autoconfiguring IPv6 router" behavior of SNAC-simple is unwanted, and
2. in mailing list discussions this "autoconfiguring" behavior was raised as a concern by some; because normally IPv6 routers only start operating after some clearly defined administration (be it manual or (semi)automated) actions;

it would be likely that a reader of SNAC-simple would need some information on this e.g. a statement that RA Guard (RFC 6105) can be used to block this behavior, if unwanted. It was decided to *not* have this in the Security Considerations but maybe there is another place for this.

**Comment by darrendukes** [comment]
Text is in an Appendix in revision 05
Reference added in 06
