### ISSUE TITLE
Do we need to make explicit that stub router itself doesn't do/need DHCPv6-PD server?

### ISSUE THREAD

**Issue by EskoDijk** [ietf-wg-snac/draft-ietf-snac-simple#8]
(Based on recent discussion in v6ops)

We don't specify yet the type of hosts on the IPv6 stub network in detail. For example, an IoT device host only needs an address which it can configure with SLAAC based on the /64 on-mesh/on-link prefix.

However, there could also be more complex hosts in principle that need their own prefixes (e.g. /64) delegated to it for internal usage and they may like to use their DHCPv6-PD client for that. For example for running multiple virtual machines / dockers inside the host where these VMs are on their own virtual network segment.

I expect these cases to be out of scope and there's no requirement on the stub router to do either DHCPv6-PD server or relay role. Do we need to make this explicit in a goal / non-goal / out-of-scope section ?

**Comment by evyncke** [comment]
With my AD hat one, I sincerely hope to keep the stub network with simple devices, else the SNAC WG will try to make a simple problem too complex ;-)

Without any hat, I do not mind having an applicability statement with non-goals in it.
