### ISSUE TITLE
Definition for "SNAC network" ?

### ISSUE THREAD

**Issue by EskoDijk** [ietf-wg-snac/draft-ietf-snac-simple#87]
In -05, the term "SNAC network" is now used but not defined.
* Could we use the more generic term "stub network" instead? I.e. a SNAC router is able to automatically connect a stub network to an infrastructure network.  So the stub network served by this SNAC router is still a "stub network".  
* Or we could use the term "SNAC network" for any stub network that gets automatically connected via a SNAC router. But doing this adds an extra term throughout the document: it's not possible to mass-replace all occurrences of "stub network".

**Comment by EskoDijk** [comment]
See also #68 which overlaps with this issue, but targets a specific definition paragraph.

**Comment by Abhayakara** [comment]
Right, this happened when we added a bunch of text in the last interim, and I think was a mistake.  I think we just want to use the term "stub network" and not invent a new term. The thing that's new here is the "SNAC router", not the stub network.

**Comment by jwhui** [comment]
I agree - "stub network" makes more sense here.

**Comment by darrendukes** [comment]
removed
