### ISSUE TITLE
Specify using IA_Prefix Hint per 8415

### ISSUE THREAD

**Issue by twintersunh** [ietf-wg-snac/draft-ietf-snac-simple#90]
OLD: 
A SNAC router SHOULD request stub network prefixes with length 64.   

New:
A SNAC router should request stub network prefixes using IA_PD with IA_Prefix with a hint of 64 as defined in RFC 8415 Section 18.3.9.

**Comment by EskoDijk** [comment]
Agree with adding the details.  Is there a reason to change SHOULD -> should ?  Seems wise to keep the SHOULD in caps given the MUST requirement that follows soon after it: 

> If the SNAC router obtains a prefix with length greater than 64, the SNAC router MUST treat the prefix as unsuitable
